openapi: 3.0.0
info:
  title: Taxengine API
  description: This API is for communication between Taxengine API and Digital Service
    Providers
  contact:
    email: sixpent@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.2
servers:
# Added by API Auto Mocking Plugin
- url: https://taxengine.psmed.org/api
  description: TAXENGINE API
tags:
- name: Digital Service Provider
  description: Operations available for registered digital service providers
paths:
  /transaction:
    post:
      tags:
      - Digital Service Provider
      summary: Add transaction
      description: Add transaction
      operationId: addTransaction
      parameters:
      - name: dsp-code
        in: header
        description: Your DSP code
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DSPNWLS
      - name: dsp-token
        in: header
        description: Your DSP token
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: HGX5LRxgkzkBRixt
      - name: dsp-secret
        in: header
        description: Your DSP secret
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: cJ1RJnoPIsavMiko3N5hQ7ky
      requestBody:
        description: Transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        "200":
          description: Transaction created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 1
                  data:
                    type: object
                    properties:
                      reference_number:
                        type: string
                        example: "0230622YHUOQ5L8AOOQZ5RLBIEENBZD4"
                      transaction_fee:
                        type: number
                        example: 19.8
                      service_fee:
                        type: number
                        example: 15
                      commission_fee:
                        type: number
                        example: 9.45
                      online_platform_vat:
                        type: number
                        example: 4.74
                      shipping_vat:
                        type: number
                        example: 4.82
                      item_vat:
                        type: number
                        example: 101.79
                      base_price:
                        type: number
                        example: 848.21
                      withholding_tax:
                        type: number
                        example: 4.24
                      tax:
                        type: number
                        example: 115.59
        "400":
          description: "ITEM_DISCREPANCY: The product status is no longer pending,\
            \ and the action is not allowed.<br> AMOUNT_DISCREPANCY:The total amount\
            \ does not match the net total.<br> MISSING_FIELD: There is a missing\
            \ required field/invalid format in the request."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "MISSING_FIELD"
        "401":
          description: "ACCESS_DENIED: Invalid secret key or authentication credentials."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "ACCESS_DENIED"
        "403":
          description: "ACTION_DENIED: The product status is no longer pending, and\
            \ the action is not allowed."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "ACTION_DENIED"
      x-swagger-router-controller: DigitalServiceProvider
  /transaction/status:
    post:
      tags:
      - Digital Service Provider
      summary: Update transaction
      description: update transaction
      operationId: updateTransaction
      parameters:
      - name: dsp-code
        in: header
        description: Your DSP code
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DSPNWLS
      - name: dsp-token
        in: header
        description: Your DSP token
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: HGX5LRxgkzkBRixt
      - name: dsp-secret
        in: header
        description: Your DSP secret
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: cJ1RJnoPIsavMiko3N5hQ7ky
      requestBody:
        description: Reference number and new status to update record
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransaction'
      responses:
        "200":
          description: Transaction updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 1
                  data:
                    type: object
                    properties:
                      reference_number:
                        type: string
                        example: "0230622YHUOQ5L8AOOQZ5RLBIEENBZD4"
                      status:
                        type: string
                        example: "ONGOING"
        "401":
          description: "ACCESS_DENIED: Invalid secret key or authentication credentials."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "ACCESS_DENIED"
        "403":
          description: "ACTION_DENIED: The action is not allowed."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "ACTION_DENIED"
      x-swagger-router-controller: DigitalServiceProvider
  /transaction/remitted: # New API endpoint "/transaction/remitted"
    post:
      tags:
        - Digital Service Provider
      summary: Set remited date on completed transactions
      description: Set remited date on completed transactions
      operationId: markTransactionsAsRemitted
      parameters:
        - name: dsp-code
          in: header
          description: Your DSP code
          required: true
          style: simple
          explode: false
          schema:
            type: string
          example: DSPNWLS
        - name: dsp-token
          in: header
          description: Your DSP token
          required: true
          style: simple
          explode: false
          schema:
            type: string
          example: HGX5LRxgkzkBRixt
        - name: dsp-secret
          in: header
          description: Your DSP secret
          required: true
          style: simple
          explode: false
          schema:
            type: string
          example: cJ1RJnoPIsavMiko3N5hQ7ky
      requestBody:
        description: An array of transaction IDs of completed transactions to be marked as remitted.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Remitted'
      responses:
        "200":
          description: List of affected trans_ids
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 1
                  data:
                    type: array
                    items:
                      type: string
                    example: ["KO12920303421", "GENP68DEWURL3J"]
        "400":
          description: "MISSING_FIELD: There is a missing\
            \ required field/invalid format in the request."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "MISSING_FIELD"
      x-swagger-router-controller: DigitalServiceProvider
components:
  schemas:
    Transaction:
      required:
      - shipping_fee
      - trans_id
      - voucher
      type: object
      properties:
        trans_id:
          type: string
          example: KO12920303421
        shipping_fee:
          type: number
          example: 45
        voucher:
          type: number
          example: 50
        coins:
          type: number
          example: 5
        subtotal_amount:
          type: number
          example: 1000
        total_amount:
          type: number
          example: 990
        status:
          type: string
          example: PENDING
        region_code:
          type: string
          example: "01"
        customer:
          $ref: '#/components/schemas/Customer'
        seller:
          $ref: '#/components/schemas/Seller'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Customer:
      type: object
      properties:
        first_name:
          type: string
          example: PATRICK
        middle_name:
          type: string
          example: ""
        last_name:
          type: string
          example: GARCIA
        mobile_number:
          type: string
          example: "09235219123"
        email:
          type: string
          example: patrickgarcia@gmail.com
        birth_date:
          type: string
          format: date
          example: 2017-07-21
    Seller:
      type: object
      required:
        - tin  # Marking the "tin" property as required
        - registered_name
        - vat_type
      properties:
        registered_name:
          type: string
          example: BritePH
        registered_address:
          type: string
          example: 123 Main St, Caloocan City
        business_name:
          type: string
          example: BritePH - Caloocan
        tin:
          type: string
          example: 260492029102
        contact_number:
          type: string
          example: "+63 912 345 6789"
        email:
          type: string
          example: testmail2@gmail.com
        vat_type:
          type: string
          example: V
    Item:
      type: object
      properties:
        description:
          type: string
          example: Samsung Galaxy Buds 2 Wireless Bluetooth Earphones Business Stereo
            Headset Noise Cancelling with Mic
        variant:
          type: string
          example: black
        qty:
          type: integer
          example: 2
        unit_price:
          type: number
          example: 500
        total_price:
          type: number
          example: 1000
    UpdateTransaction:
      required:
      - reference_number
      - status
      type: object
      properties:
        reference_number:
          type: string
          example: SP0EFN9BOOMCOXUAMTMJBYN1LVKUABQH
        status:
          type: string
          example: ONGOING
    Remitted:
      type: object
      properties:
        trans_ids:
          type: array
          items:
            type: string
          example: ["KO12920303421", "GENP68DEWURL3J", "GTXSDTT9K052T", "KO12920303421"]
          description: An array of transaction IDs of completed transactions to be marked as remitted.
        remitted_date:
          type: string
          format: date-time
          example: "2023-07-25 10:24:00"